INSERT INTO genres VALUES (1, POP);
INSERT INTO genres VALUES (2, ROCK);
INSERT INTO genres VALUES (3, RUSSIAN ROCK);
INSERT INTO genres VALUES (4, RAP);
INSERT INTO genres VALUES (5, ELECTRON);

INSERT INTO ARTISTS VALUES (1, LANA DEL REY);
INSERT INTO ARTISTS VALUES (2, Joe Cocker);
INSERT INTO ARTISTS VALUES (3, Nickelback);
INSERT INTO ARTISTS VALUES (4, KINO);
INSERT INTO ARTISTS VALUES (5, DRAKE);
INSERT INTO ARTISTS VALUES (6, MOBY);
INSERT INTO ARTISTS VALUES (7, DAFT PUNK);
INSERT INTO ARTISTS VALUES (8, DDT);
INSERT INTO ARTISTS VALUES (9, AC/DC);

INSERT INTO genre-artist VALUES (1, 1);
INSERT INTO genre-artist VALUES (1, 2);
INSERT INTO genre-artist VALUES (2, 2);
INSERT INTO genre-artist VALUES (2, 3);
INSERT INTO genre-artist VALUES (2, 4);
INSERT INTO genre-artist VALUES (2, 8);
INSERT INTO genre-artist VALUES (2, 9);
INSERT INTO genre-artist VALUES (3, 4);
INSERT INTO genre-artist VALUES (3, 8);
INSERT INTO genre-artist VALUES (4, 5);
INSERT INTO genre-artist VALUES (5, 7);
INSERT INTO genre-artist VALUES (5, 6);

INSERT INTO albums VALUES (1, GRUPPA KROVI, 1988);
INSERT INTO albums VALUES (2, Unchain My Heart, 1986);
INSERT INTO albums VALUES (3, Chemtrails Over The Country Club, 2018);
INSERT INTO albums VALUES (4, Silver Side Up, 2001);
INSERT INTO albums VALUES (5, Certified Lover Boy, 2021);
INSERT INTO albums VALUES (6, Play, 1999);
INSERT INTO albums VALUES (7, Random Access Memories, 2013);
INSERT INTO albums VALUES (8, Творчество в пустоте, 2021);
INSERT INTO albums VALUES (9, Highway to Hell, 1979);

INSERT INTO artist-album VALUES (1, 4);
INSERT INTO artist-album VALUES (2, 2);
INSERT INTO artist-album VALUES (3, 1);
INSERT INTO artist-album VALUES (4, 3);
INSERT INTO artist-album VALUES (5, 5);
INSERT INTO artist-album VALUES (6, 6);
INSERT INTO artist-album VALUES (7, 7);
INSERT INTO artist-album VALUES (8, 8);
INSERT INTO artist-album VALUES (9, 9);

INSERT INTO Collection VALUES (1, ROCK, 2018);
INSERT INTO Collection VALUES (2, 100 GREATEST, 2020);
INSERT INTO Collection VALUES (3, ROMANTIC, 2021);
INSERT INTO Collection VALUES (4, COOL, 2019);
INSERT INTO Collection VALUES (5, CLUBBING ANTHEMS, 2020);
INSERT INTO Collection VALUES (6, LEGENDARY SONGS, 2020);
INSERT INTO Collection VALUES (7, RUSSIAN BALLADS, 2022);
INSERT INTO Collection VALUES (8, CLASSIC POP, 2020);

INSERT INTO tracks (id_track, track_name, track_length) VALUES (1, SONG 2, 122);
INSERT INTO tracks VALUES (2, 4, How You Remind Me, 223);
INSERT INTO tracks VALUES (3, 6, Natural Blues, 253);
INSERT INTO tracks VALUES (4, 9, Touch Too Much, 266);
INSERT INTO tracks VALUES (5, 2, Unchain My Heart, 304);
INSERT INTO tracks VALUES (6, 3, Tulsa Jesus Freak, 215);
INSERT INTO tracks VALUES (7, 5, Fair Trade, 291);
INSERT INTO tracks VALUES (8, 5, Way 2 Sexy, 257);
INSERT INTO tracks VALUES (9, 7, Get Lucky, 369);
INSERT INTO tracks VALUES (10, 7, Lose Yourself to Dance, 353);
INSERT INTO tracks VALUES (11, 9, Thunderstruck, 292);
INSERT INTO tracks VALUES (12, 9, Back in Black, 255);
INSERT INTO tracks VALUES (13, 1, Группа крови, 283);
INSERT INTO tracks VALUES (14, 8, Где я, 331);
INSERT INTO tracks (id_track, track_name, track_length) VALUES (15, Dont Speak, 262);

INSERT INTO Collection-tracks VALUES (1, 1);
INSERT INTO Collection-tracks VALUES (1, 2);
INSERT INTO Collection-tracks VALUES (2, 3);
INSERT INTO Collection-tracks VALUES (2, 4);
INSERT INTO Collection-tracks VALUES (3, 5);
INSERT INTO Collection-tracks VALUES (3, 6);
INSERT INTO Collection-tracks VALUES (4, 7);
INSERT INTO Collection-tracks VALUES (4, 8);
INSERT INTO Collection-tracks VALUES (5, 9);
INSERT INTO Collection-tracks VALUES (5, 10);
INSERT INTO Collection-tracks VALUES (6, 11);
INSERT INTO Collection-tracks VALUES (6, 12);
INSERT INTO Collection-tracks VALUES (7, 13);
INSERT INTO Collection-tracks VALUES (7, 14);
INSERT INTO Collection-tracks VALUES (8, 15);